services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

  frontend:
    build: ./nyc-taxi-2017-frontend
    ports:
      - "3000:3000"
    depends_on:
      - app

  db:
    image: "postgres:latest"
    hostname: db
    ports:
      - "5432:5432"
    volumes:
      - "./nyc-psql-db:/var/lib/postgresql/data"