version: "2"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - "./../nyc-psql-rides-db:/var/lib/postgresql/data"
    env_file:
      - ./../nyc-taxi.env

